### ISSUE TITLE
Feedback on presentation video

### ISSUE THREAD

**Issue by jordy248** [dvaconquerors/final-project-proposal#1]
Hi, @AlexMabry @caldwellst @guenter-r @mjkanji @daeminsong!

Here's a link to the presentation test @daeminsong put together:
https://www.youtube.com/watch?v=q6iwxPZ1oeY

As we talked about this past weekend, let's all plan on watching it again and providing some feedback in this issue by Wednesday. 

- [ ] @AlexMabry 
- [ ] @caldwellst 
- [ ] @guenter-r 
- [ ] @mjkanji 
- [x] @jordy248

**Comment by guenter-r** [comment]
I think the video is great, that is definitely the way we should go - thanks Daemin! I would add that we incorporate the findings of our additional datasets to our models (I try to be quite vague), **just to avoid that it sounds like we just show these factors on top** but don't do any sort of analysis, number crunching, etc.

**Comment by caldwellst** [comment]
Yep, agreed, otherwise looks good to me. I went through and I think the Heilmeier questions are sufficiently answered. My only concerns would be around 4/5. Would it be good to add a point something like "despite the large academic literature available, the pricing models deployed and used today are not publicly shared and generally only available to sellers". This could lead into the information assymetry slide. But don't think is too critical if it doesn't make it in.

**Comment by caldwellst** [comment]
As well, do we need more detail on the slides in regard to the progress plan and milestone, akin to what is now in the proposal?

**Comment by jordy248** [comment]
@daeminsong -- agreed with Guenter and Seth that this is great! 😄 

My only additional feedback is that I wonder if it's possible to briefly expand the literature review a tiny bit? I think Seth's comment above ("despite academic literature available...") gets at this, and I also wonder if it's worth briefly mentioning some studies that have tried including external factors -- i.e., datasets obtained from outside of Zillow -- to (1) bulk up the lit review a little bit and (2) make it clear that we're not just recreating Zillow with Zillow data.

I also wonder if it would be worth adding some citations to the bottom of slides as you talk just to get some more references in the video. (I don't think that you'd necessarily even have to talk about them -- I think that just putting them there shows that we've done the research and they're informing the project.) For instance:
* Problem description in beginning: 
    * Goodman2018 relates to this (difficulties households face in buying a home)
* "Algorithms not working as well as you'd like" in beginning
    * Anselin2006 (talks about difficulty of interpolating samples at fixed locations to geographically dispersed observations)
    * Francke2017 (talks about the normal error used in most hedonic regression models of home prices may not be warranted and probably should be replaced by t-distribution to better deal with outliers)
    * Chen2017, Chen2019, Zheng2014 (talk about endogeneity of air quality and price in the Chinese housing market because of reverse causality: home prices naturally increase in regions characterized by lots of heavy industry -- which increases both wealth and pollution)
    * Carriazo2018 (talks about the importance of using **both** stages of Rosen's 1974 hedonic pricing frameworks but notes that most studies only use first stage)
    * Bayer2009 (talks about the importance of including buyer mobility constraints in hedonic homepricing models)
    * Chen2017 (talks about using a multilevel/fixed effects approach for homes in different cities; also talks a bit about the importance of using log-linear functional form to mitigate heteroscedasticity that is often present in real estate prices)
    * Morano2019 (talks about using an evolutionary polynomial approach to fit a model that services multiple regions)
* Literature survey
    * Under "regression" to get a few more references in, we could maybe add some sub-bullet points for:
        * Hedonic regression: Rosen1974, 
        * Bayesian temporal regression: Francke2017
        * Multilevel regression: Chen2017, Chen2019
        * General multilevel regression: Gelman2007
        * General Bayesian regression: Gelman2014
        
For the Heilmeier questions:
* Do we think it's worth including little tags on the slides as you address the Heilmeier questions so it's obvious to the TAs that we're including them?
* For cost, we can probably say we don't anticipate it costing anything and that our time investment is the only cost
* RE: Seth's point about questions 4 and 5, I agree that we could probably mention that this project is important to homebuyers (because buying a home is an emotional process and we want to reduce regrets).

**Comment by daeminsong** [comment]
Thank you gentlemen. Here is the updated one - [https://youtu.be/UD_OxX_d9bA](https://youtu.be/UD_OxX_d9bA). We will go from here.

**Comment by AlexMabry** [comment]
This looks great!

**Comment by mjkanji** [comment]
Agreed, it looks great! And I definitely think it'd be great if we could incorporate some of Jordy's suggestions into the video.

I will mention again, though, that the volume is pretty low. If you have a dedicated mic you could use, that'd be really helpful.

**Comment by daeminsong** [comment]
@mjkanji -- Muhammad, just wondering if you watched the updated one? I'm asking because it reflects most of Jordy's suggestions (couldn't include all of them due to space + time limitations if that's what you meant). 

And I'm using a dedicated [mic](https://apogeedigital.com/products/one),  but I don't have a pop filter at this moment so can't really add more gains so we kind of have to go with this level. I guess the worst case I can increase gain level in Garage band or something, but not sure if it's necessary.
